### ISSUE TITLE
Question on local backend username and password Labels 

### ISSUE THREAD

**Issue by samcro1967** [greenpau/caddy-auth-portal#126]
**Describe the issue**
I never see the log entries for:
{"level":"info","ts":1588704471.5784082,"logger":"http.authentication.providers.portal","msg":"created new user","user_id":"cd5f647a-cc04-4ae2-9d0a-2d5e9b95cf98","user_name":"webadmin","user_email":"webadmin@localdomain.local","user_claims":{"roles":"superadmin"}}
{"level":"info","ts":1588704471.5784378,"logger":"http.authentication.providers.portal","msg":"created default superadmin user for the database","user_name":"webadmin","user_secret":"d87e7749-0dd8-482b-91a2-ada370263293"}

The users.json file does get created and webadmin does exist.

**A clear and concise description of what the issue is.**
Unable to login using local backend due to unknown password.  I also tried to copied the basic auth hash password I created a few years ago as I think caddy v1 used bcrypt also.  It does not work either.  Not able to get bcrypt installed on Ubuntu and it does not appear to be n the caddy container also.  Struggling trying to figure out how to get the password set correctly.

**Caddy Dockerfile**
```
ARG CADDY_VERSION=2.4.0
FROM caddy:${CADDY_VERSION}-builder AS builder
RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 \
    --with github.com/greenpau/caddy-auth-portal \
    --with github.com/greenpau/caddy-auth-jwt \
    --with github.com/greenpau/caddy-trace \
FROM caddy:${CADDY_VERSION}-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
CMD ["caddy", "docker-proxy"]
```
**docker-compose**
```
version: '3.8'
services:  caddy:
    image: xcaddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - CADDY_DOCKER_CADDYFILE_PATH=/data/CaddyFile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${docker}/caddy2/data:/data"
      - "${docker}/caddy2/config:/config"
```
**Caffyfile Configuration**
```
{
  https_port    8443
  debug
}
192.168.1.104:8443 {
  route /auth* {
    auth_portal {
      path /auth
      backends {
        local_backend {
          method local
          path /config/caddy/users.json
          realm local
        }
      }
      jwt {
        token_name access_token
        token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
      }
      ui {
        links {
          "homeauto" /homeauto
        }
      }
    }
  }
route /homeauto* {
    jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name access_token
          token_secret 0e2fdcf8-6868-41a7-884b-7308795fc286
        }
      }
      auth_url /auth
      allow roles anonymous guest admin
      allow roles superadmin
    }
    uri strip_prefix /homeauto
    reverse_proxy 192.168.1.157:80
  }
}
```
**Version Information**
```
/srv # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.0
http.authentication.hashes.scrypt v2.4.0
http.authentication.providers.http_basic v2.4.0
http.handlers.authentication v2.4.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
/srv #
```
