### ISSUE TITLE
Question:  How to get apps without url baser/prefix capability to work

### ISSUE THREAD

**Issue by samcro1967** [greenpau/caddy-auth-portal#128]
**Describe the issue**

I am not quite sure how to get apps without the ability to have a url base/prefix to work.  Without caddy-auth-portal, I would just do one route statement to do a reverse proxy.  I have tried uri strip_prefix that I saw in the documentation example with 2 different apps, but neither works.  Any suggestions on what else to try?

**Configuration**

**Caddy Dockerfile**
```
ARG CADDY_VERSION=2.4.0
FROM caddy:${CADDY_VERSION}-builder AS builder
RUN xcaddy build \
    --with github.com/lucaslorentz/caddy-docker-proxy/plugin/v2 \
    --with github.com/greenpau/caddy-auth-portal \
    --with github.com/greenpau/caddy-auth-jwt \
    --with github.com/greenpau/caddy-trace \
   --with github.com/porech/caddy-maxmind-geolocation
FROM caddy:${CADDY_VERSION}-alpine
COPY --from=builder /usr/bin/caddy /usr/bin/caddy
CMD ["caddy", "docker-proxy"]
```
**docker-compose**
```
version: '3.8'
services:  caddy:
    image: xcaddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
      - CADDY_DOCKER_CADDYFILE_PATH=/data/CaddyFile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${docker}/caddy2/data:/data"
      - "${docker}/caddy2/config:/config"
  test:
    image: linuxserver/test:latest
    container_name: test
    volumes:
     - "${docker}/test/data:/config"
     - "${downloads}/:/downloads"
    environment:
     - TZ=America/Chicago
     - PUID=1000
     - PGID=1000
    network_mode: "service:wireguard-pia"
    depends_on:
      - wireguard-pia
    labels:
     - caddy_0= "http://local.text"
     - caddy_0.route.reverse_proxy= "192.168.1.104:8097"
     - caddy_0.tls= "internal"
     - caddy_1= "auth.mydomain.net"
     - caddy_1.route= "/test*"
     - caddy_1.route.jwt
     - caddy_1.route.0_uri= strip_prefix /test
     - caddy_1.route.1_reverse_proxy= @mygeofilter 192.168.1.104:8097
  wireguard-pia:
    image: thrnz/docker-wireguard-pia
    container_name: wireguard-pia
    networks:
      wg-pia:
    ports:
     - "8097:5076" # port mapping test
    cap_add:
     - NET_ADMIN
    volumes:
     - "${docker}/wireguard-calibre/pia:/pia"
     - "${docker}/wireguard-calibre/pia:/pia-shared"
    environment:
     - TZ=America/Chicago
     - PUID=1000
     - PGID=1000
     - USER=<redacted>
     - PASS=<redacted>
     - LOC=us_chicago
     - LOCAL_NETWORK=192.168.1.0/24
```
**Caffyfile Configuration**
```
{
        https_port 443
        http_port 80
        debug
        email user@mydoamin.net
}
(geofilter) {
        @mygeofilter {
                maxmind_geolocation {
                        db_path /data/GeoLite2-Country.mmdb
                        allow_countries US
                }
        }
}
auth.mydoamin.net {
        import geofilter
        log {
                output file /data/access.log
        }
        route /auth* {
                auth_portal {
                        path /auth
                        backends {
                                local_backend {
                                        method local
                                        path /config/caddy/users.json
                                        realm local
                                        require mfa
                                }
                        }
                        jwt {
                                token_name access_token
                                token_secret <redacted>
                                token_lifetime 3600
                        }
                        registration {
                                dropbox /config/caddy/registrations_db.json
                                title "User Registration"
                                code <redacted>
                                require accept_terms
                                require domain_mx
                        }
                        ui {
                                links {
                                        "My Identity" /auth/whoami icon "las la-star"
                                        "My Settings" /auth/settings icon "las la-cog"
                                        "My Versions" /version icon "las la-smile"
                                        Test /test icon "las la-search"
                                        Main /main icon "las la-search"
                                }
                        }
                }
        }
        route /main* {
                jwt {
                        primary yes
                        trusted_tokens {
                                static_secret {
                                        token_name access_token
                                        token_secret <redacted>
                                }
                        }
                        auth_url /auth
                        allow roles anonymous guest admin
                        allow roles superadmin
                }
                reverse_proxy @mygeofilter 192.168.1.157:80
        }
        route /version* {
                respond * `caddy v2.4.0 h1:yHnnbawH2G3ZBP2mAJF4XBLnJanqhULLP/wu01Qi9Io=
http.authentication.hashes.bcrypt v2.4.0
http.authentication.hashes.scrypt v2.4.0
http.authentication.providers.http_basic v2.4.0
http.handlers.authentication v2.4.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
http.matchers.maxmind_geolocation v0.0.0-20201011164607-088c2173a367` 200
        }
        route {
                redir https://{hostport}/auth/ 302
        }
        route /test* {
                uri strip_prefix /test
                reverse_proxy @mygeofilter 192.168.1.104:8097
                jwt
        }
}
```
**Version Information**
```
/srv # caddy list-modules -versions | grep auth
http.authentication.hashes.bcrypt v2.4.0
http.authentication.hashes.scrypt v2.4.0
http.authentication.providers.http_basic v2.4.0
http.handlers.authentication v2.4.0
http.authentication.providers.jwt v1.2.7
http.handlers.auth_portal v1.4.6
/srv #
```

**Logs from 2 different apps I tried that failed**
```


{"level":"info","ts":1621720114.5804756,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_addr":"23.xxx.xxx.107:50100","proto":"HTTP/2.0","method":"GET","host":"auth.mydomain.net","uri":"/auth/portal","headers":{"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""],"Sec-Ch-Ua-Mobile":["?0"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"],"Sec-Fetch-Site":["same-origin"],"Sec-Fetch-Mode":["no-cors"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.9"],"Cookie":["AUTH_PORTAL_SANDBOX=x70j5mwr77yqt12uh43a0jvw4e1h7eo1ks28k8a6qa6fcbtbrthnkvcg0hkm5uztifyfbbpa1g1er7ybsmlqtkb4jp4oh; access_token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE3MjMzODIsImp0aSI6ImEzY2Y2ZGIxLWQzYWYtNGU3NS05M2ZhLTlmZjJmZDE2NDYwZiIsImlhdCI6MTYyMTcxOTc5NSwiaXNzIjoiaHR0cHM6Ly9hdXRoLm9zdWhpY2tleXMubmV0L2F1dGgvc2FuZGJveC9qOW0zYTVvemFzdGFzZ2s4M2Q5N2pmMDhraXdheGhub3RyM3F4b3Z2NTJlc2J6dzYxYzdmZTRhNW90bmhibzhvNzZ5dHcwdWs0ZzRiaGd6ODFoL3N0YXR1cyIsInN1YiI6Im9zdWhpY2tleXMiLCJlbWFpbCI6IndlYmFkbWluQGxvY2FsZG9tYWluLmxvY2FsIiwicm9sZXMiOlsic3VwZXJhZG1pbiIsImd1ZXN0IiwiYW5vbnltb3VzIl0sIm9yaWdpbiI6ImxvY2FsaG9zdCIsIm1ldGFkYXRhIjp7Im1mYV9hdXRoZW50aWNhdGVkIjp0cnVlfX0.1LNcPbES9BAHR94LxzOTBWsueHSafXcl4o444VtndRZ4eqCFD3zaZas58XsM0LMCilDm2ix8vVDKzNUHZCTDYQ; HYDRA-XSRF-TOKEN=8c2ce52e-af81-4bdc-9834-acc8e75dccc1"],"Accept":["image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"],"Sec-Fetch-Dest":["image"],"Referer":["https://auth.mydomain.net/hubitat"]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"auth.mydomain.net"}},"common_log":"23.xxx.xxx.107 - - [22/May/2021:21:48:34 +0000] \"GET /auth/portal HTTP/2.0\" 200 4704","duration":0.000385805,"size":4704,"status":200,"resp_headers":{"Server":["Caddy"],"Content-Type":["text/html"]}}

{"level":"info","ts":1621720075.0821524,"logger":"http.log.access.log0","msg":"handled request","request":{"remote_addr":"23.xxx.xxx.107:50100","proto":"HTTP/2.0","method":"GET","host":"auth.mydomain.net","uri":"/auth/portal","headers":{"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"],"Accept":["image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"],"Sec-Fetch-Site":["same-origin"],"Accept-Language":["en-US,en;q=0.9"],"Cookie":["AUTH_PORTAL_SANDBOX=x70j5mwr77yqt12uh43a0jvw4e1h7eo1ks28k8a6qa6fcbtbrthnkvcg0hkm5uztifyfbbpa1g1er7ybsmlqtkb4jp4oh; access_token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjE3MjMzODIsImp0aSI6ImEzY2Y2ZGIxLWQzYWYtNGU3NS05M2ZhLTlmZjJmZDE2NDYwZiIsImlhdCI6MTYyMTcxOTc5NSwiaXNzIjoiaHR0cHM6Ly9hdXRoLm9zdWhpY2tleXMubmV0L2F1dGgvc2FuZGJveC9qOW0zYTVvemFzdGFzZ2s4M2Q5N2pmMDhraXdheGhub3RyM3F4b3Z2NTJlc2J6dzYxYzdmZTRhNW90bmhibzhvNzZ5dHcwdWs0ZzRiaGd6ODFoL3N0YXR1cyIsInN1YiI6Im9zdWhpY2tleXMiLCJlbWFpbCI6IndlYmFkbWluQGxvY2FsZG9tYWluLmxvY2FsIiwicm9sZXMiOlsic3VwZXJhZG1pbiIsImd1ZXN0IiwiYW5vbnltb3VzIl0sIm9yaWdpbiI6ImxvY2FsaG9zdCIsIm1ldGFkYXRhIjp7Im1mYV9hdXRoZW50aWNhdGVkIjp0cnVlfX0.1LNcPbES9BAHR94LxzOTBWsueHSafXcl4o444VtndRZ4eqCFD3zaZas58XsM0LMCilDm2ix8vVDKzNUHZCTDYQ; HYDRA-XSRF-TOKEN=8c2ce52e-af81-4bdc-9834-acc8e75dccc1"],"Sec-Ch-Ua-Mobile":["?0"],"Sec-Fetch-Mode":["no-cors"],"Sec-Fetch-Dest":["image"],"Accept-Encoding":["gzip, deflate, br"],"Sec-Ch-Ua":["\" Not A;Brand\";v=\"99\", \"Chromium\";v=\"90\", \"Google Chrome\";v=\"90\""]},"tls":{"resumed":true,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"auth.mydomain.net"}},"common_log":"23.xxx.xxx.107 - - [22/May/2021:21:47:55 +0000] \"GET /auth/portal HTTP/2.0\" 200 4704","duration":0.000387806,"size":4704,"status":200,"resp_headers":{"Server":["Caddy"],"Content-Type":["text/html"]}}
```
