### ISSUE TITLE
Caddy OAuth with gitlab as provider

### ISSUE THREAD

**Issue by copolycube** [greenpau/caddy-auth-portal#140]
**Describe the issue**

follow-up on https://caddy.community/t/gitlab-oauth-provider/12583/10

==> how should I configure a Caddyfile and caddy docker image so that I can delegate the OAuth to gitlab.

**Configuration**

```
127.0.0.1, localhost {
  route /auth* {
    authp {
      backends {
        generic_oauth2_backend {
          method oauth2
          realm generic
          provider generic
          client_id <gitla application ID>
          client_secret <gitlab application secret>
          scopes openid email profile
        }
  route /sso/oauth2/generic* {
    jwt {
      auth_url /auth/oauth2/generic
    }
    respond * "generic oauth2 sso" 200
  }

prometheus.jump.<domain>.com {
        jwt {
      primary yes
      trusted_tokens {
        static_secret {
          token_name access_token
          token_secret <????>
        }
      }
      auth_url /auth
      allow roles anonymous guest admin
      allow roles superadmin
    }
    reverse_proxy prometheus:9090
}

alertmanager.jump.<domain>.com {
    jwt
    reverse_proxy alertmanager:9093
}
```

**Version Information**

 

    Dockerfile (full):

```
ARG image_ref
FROM $image_ref-builder AS builder

RUN xcaddy build \
    --with github.com/greenpau/caddy-auth-jwt \
    --with github.com/greenpau/caddy-auth-portal \
    --with github.com/greenpau/caddy-trace

FROM $image_ref

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

    docker-compose.yml (extract, initially adapted from dockprom docker-compose) :

```
  caddy:
    build:
        context : ./caddy
        dockerfile: Dockerfile
        args:
            image_ref : caddy:2.3.0
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
    env_file:
      ./.env
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-JDJhJDE0JE91S1FrN0Z0VEsyWmhrQVpON1VzdHVLSDkyWHdsN0xNbEZYdnNIZm1pb2d1blg4Y09mL0ZP}
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
```

But this results in an error
`github.com/greenpau/caddy-auth-jwt/pkg/claims: module github.com/greenpau/caddy-auth-jwt@latest found (v1.3.3), but does not contain package github.com/greenpau/caddy-auth-jwt/pkg/claims`

**Expected behavior**

OAuth with gitlab as the OAuth provider, restricted to a gitlab group (application declared at the gitlab group level).

**Additional context**

* initial question on Caddy community forum : cf . https://caddy.community/t/gitlab-oauth-provider/12583/10
* gitlab application / oauth provider :  https://docs.gitlab.com/ee/integration/oauth_provider.html
