### ISSUE TITLE
question: How do I use the provided Docker container?

### ISSUE THREAD

**Issue by mindfuucker** [greenpau/caddy-auth-portal#199]
Building Caddy from scratch seemed a bit difficult so I wanted to use the provided Docker container. 
I am using Docker Compose to organise my containers and made this docker-compose.yml file:
```
version: "3"
services:
  caddy-auth:
    image: ghcr.io/greenpau/caddy-auth-portal:latest
    container_name: caddy
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./config:/etc/caddy
      - ./users:/etc/gatekeeper/auth/local
    ports:
      - 443:433
      - 8080:80
      - 2019:2019
    restart: unless-stopped
```
**What am I missing:**
-

- Some documentation about the interfaces of the container. What volumes do I need to bind and what ports do I need to expose?
- How do I reach the admin enpoint? I have tried https://DockerHostIP:2019, https://DockerHostIP:2019/auth, https://DockerHostIP:2019/auth/settings
- After copying [the whole usage example](https://authp.github.io/docs/authenticate/usage-examples) (changing 8443->433, 8080->80) into my Caddyfile I tried to reach https://DockerHostIP/auth and got nothing. 
- Docker is running, http://DockerHostIP:8080 does give me the Caddy welcome screen. 
- How do I use this container and how do I expose it secrets?
- What would be a minimal viable Caddyfile configuration from which I can build upon?

Here is my Docker Log, it might help?? [caddydockerlog.txt](https://github.com/greenpau/caddy-auth-portal/files/7530009/caddydockerlog.txt)
